import 'bootstrap/dist/css/bootstrap.css';
import './globals.css'
import BootstrapClient from '@/app/components/BootstrapClient';
import {} from 'next/font/google';
import { Roboto_Condensed } from 'next/font/google';

const roboto_condensed = Roboto_Condensed({ subsets:['latin']})


export const metadata = {
  title: 'Fabio Squizzato',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto_condensed.className}>
        {children}
        <BootstrapClient />
      </body>
    </html>
  )
}